# NumPy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

## Array

In [3]:
ages = [20, 35, 25, 23, 41, 29]
print(ages, type(ages))

[20, 35, 25, 23, 41, 29] <class 'list'>


In [4]:
other_ages = [21, 24, 39, 33, 21, 32]
print(other_ages, type(other_ages))

[21, 24, 39, 33, 21, 32] <class 'list'>


In [5]:
ages + other_ages

[20, 35, 25, 23, 41, 29, 21, 24, 39, 33, 21, 32]

Define array 1D

In [6]:
np_ages = np.array(ages)
print(np_ages)
print(type(np_ages))

[20 35 25 23 41 29]
<class 'numpy.ndarray'>


In [7]:
np_other_ages = np.array(other_ages)
print(np_other_ages)

[21 24 39 33 21 32]


In [8]:
sum_ages = np_ages + np_other_ages
print(np_ages, "+", np_other_ages)
print(sum_ages)

[20 35 25 23 41 29] + [21 24 39 33 21 32]
[41 59 64 56 62 61]


In [22]:
np.array([1, 2]) + np.array([2, 2, 3])

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [23]:
np.array([1, 2]) + 2

array([3, 4])

In [24]:
np.array([1, 2]) + np.array([2])

array([3, 4])

In [9]:
next_year = 1
ages_next_year = np_ages + next_year
print(ages_next_year)

[21 36 26 24 42 30]


Define array 2D

In [11]:
randoms = [[0, 1, 2], [3, 4, 5]]
print(randoms, type(randoms))

[[0, 1, 2], [3, 4, 5]] <class 'list'>


In [12]:
np_randoms = np.array(randoms)
print(type(np_randoms))
print(np_randoms)

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]]


In [13]:
np_ones = np.array([[1, 1], [1, 1], [1, 1]])
print(np_ones)

[[1 1]
 [1 1]
 [1 1]]


Generate array full of zeros

In [14]:
zeros_10_10 = np.zeros((10, 10))
print(zeros_10_10)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Generate array full of ones

In [15]:
ones_10_10 = np.ones((10, 10))
print(ones_10_10)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
print(np_ages)
print("shape:", np_ages.shape)
print("num of dimensions:", np_ages.ndim)
print("num of elements:", np_ages.size)

[20 35 25 23 41 29]
shape: (6,)
num of dimensions: 1
num of elements: 6


In [26]:
print(np_ones)
print("shape:", np_ones.shape)
print("num of dimensions:", np_ones.ndim)
print("num of elements:", np_ones.size)

[[1 1]
 [1 1]
 [1 1]]
shape: (3, 2)
num of dimensions: 2
num of elements: 6


Array 3D

In [28]:
nd_array = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[11, 12, 13], [14, 15, 16], [17, 18, 19]]
])
print(nd_array)
print("shape:", nd_array.shape)
print("num of dimensions:", nd_array.ndim)
print("num of elements:", nd_array.size)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]
shape: (2, 3, 3)
num of dimensions: 3
num of elements: 18


In [29]:
array_4d = np.array([
    [[[1], [2], [3]], [[4], [5], [6]], [[7], [8], [9]]],
    [[[11], [12], [13]], [[14], [15], [16]], [[17], [18], [19]]]
])
print(array_4d)
print("shape:", array_4d.shape)
print("num of dimensions:", array_4d.ndim)
print("num of elements:", array_4d.size)

[[[[ 1]
   [ 2]
   [ 3]]

  [[ 4]
   [ 5]
   [ 6]]

  [[ 7]
   [ 8]
   [ 9]]]


 [[[11]
   [12]
   [13]]

  [[14]
   [15]
   [16]]

  [[17]
   [18]
   [19]]]]
shape: (2, 3, 3, 1)
num of dimensions: 4
num of elements: 18


In [35]:
np.array([[1, 1, 2, 2]]).shape, np.array([[1, 1, 2, 2]]).ndim, np.array([[1, 1, 2, 2]]).size

((1, 4), 2, 4)

In [36]:
np.array([[[1, 1, 2, 2]]]).shape, np.array([[[1, 1, 2, 2]]]).ndim, np.array([[[1, 1, 2, 2]]]).size

((1, 1, 4), 3, 4)

In [39]:
print(nd_array)
print(nd_array.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]
(2, 3, 3)


In [42]:
np.reshape(nd_array, (3, 3, 2))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 11],
        [12, 13]],

       [[14, 15],
        [16, 17],
        [18, 19]]])

In [44]:
# will throw error
# np.reshape(nd_array, (3, 3, 3))

In [45]:
print(np_ages)
print(np_ages.shape)

[20 35 25 23 41 29]
(6,)


In [47]:
print(np.reshape(np_ages, (1, 6)))
print(np.reshape(np_ages, (6, 1)))
print(np.reshape(np_ages, (2, 3)))
print(np.reshape(np_ages, (3, 2)))
print(np.reshape(np_ages, (2, 3, 1)))
print(np.reshape(np_ages, (3, 2, 1)))
print(np.reshape(np_ages, (1, 6, 1)))
print(np.reshape(np_ages, (1, 1, 6)))

[[20 35 25 23 41 29]]
[[20]
 [35]
 [25]
 [23]
 [41]
 [29]]
[[20 35 25]
 [23 41 29]]
[[20 35]
 [25 23]
 [41 29]]
[[[20]
  [35]
  [25]]

 [[23]
  [41]
  [29]]]
[[[20]
  [35]]

 [[25]
  [23]]

 [[41]
  [29]]]
[[[20]
  [35]
  [25]
  [23]
  [41]
  [29]]]
[[[20 35 25 23 41 29]]]


In [48]:
print(np.reshape(np_ages, (1, 1, 1, 1, 6)))

[[[[[20 35 25 23 41 29]]]]]


## Indexing

Indexing in list..

In [49]:
ages = [[20, 35, 25], [23, 41, 29]]
print(ages)

[[20, 35, 25], [23, 41, 29]]


In [51]:
ages[-1][-1]

29

In [53]:
ages[-1][:2]

[23, 41]

In [55]:
ages[0][-2:]

[35, 25]

Indexing array...

In [56]:
np_ages = np.array(ages)
print(np_ages)

[[20 35 25]
 [23 41 29]]


In [57]:
np_ages[-1, -1]

29

In [58]:
np_ages[0, -2:]

array([35, 25])

In [63]:
np_ages[:, 0]

array([20, 23])

In [64]:
np_ages[:, 1]

array([35, 41])

In [60]:
print(nd_array)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]


In [61]:
nd_array[-1, 1, 1]

15

In [66]:
nd_array[:, 0, 0]

array([ 1, 11])

In [68]:
nd_array[:, [0, 1], [0, 1]]

array([[ 1,  5],
       [11, 15]])

In [69]:
nd_array.shape

(2, 3, 3)

In [71]:
nd_array[np.newaxis, :].shape

(1, 2, 3, 3)

In [73]:
nd_array[:, :, :, np.newaxis].shape

(2, 3, 3, 1)

In [74]:
nd_array[:, np.newaxis, :, :].shape

(2, 1, 3, 3)

In [76]:
nd_array[:, :, np.newaxis, :, np.newaxis].shape

(2, 3, 1, 3, 1)

In [80]:
nd_array[None, :].shape

(1, 2, 3, 3)

In [81]:
nd_array[:, :, None, :].shape

(2, 3, 1, 3)

In [82]:
np_ages

array([[20, 35, 25],
       [23, 41, 29]])

In [83]:
min_age = 25

np_ages[np_ages <= 25]

array([20, 25, 23])

In [84]:
np_ages <= 25

array([[ True, False,  True],
       [ True, False, False]])

In [87]:
np_ages[[[True, False, True], [True, False, False]]]

array([20, 25, 23])

In [95]:
np.argwhere(np_ages <= 25)

array([[0, 0],
       [0, 2],
       [1, 0]])

## Array Concatenation

In [98]:
np_ages.shape

(2, 3)

In [99]:
np_ones.shape

(3, 2)

In [100]:
np_ages.T

array([[20, 23],
       [35, 41],
       [25, 29]])

In [101]:
np_ages.transpose()

array([[20, 23],
       [35, 41],
       [25, 29]])

In [103]:
np.vstack((np_ages, np_ones.T))

array([[20, 35, 25],
       [23, 41, 29],
       [ 1,  1,  1],
       [ 1,  1,  1]])

In [105]:
np_other_ages = np.array([
    [31, 33, 30],
    [21, 33, 20],
    [31, 32, 30],
])
print(np_other_ages)

[[31 33 30]
 [21 33 20]
 [31 32 30]]


In [106]:
np.vstack((np_ages, np_other_ages))

array([[20, 35, 25],
       [23, 41, 29],
       [31, 33, 30],
       [21, 33, 20],
       [31, 32, 30]])

In [108]:
np.hstack((np_ones, np_other_ages))

array([[ 1,  1, 31, 33, 30],
       [ 1,  1, 21, 33, 20],
       [ 1,  1, 31, 32, 30]])

In [110]:
print(nd_array)
print(nd_array.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]
(2, 3, 3)


In [116]:
np.vstack((nd_array, np_ages[:, np.newaxis, :]))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 1

## Array Operations

In [117]:
np_ages

array([[20, 35, 25],
       [23, 41, 29]])

In [118]:
np.sum(np_ages)

173

In [119]:
np_ages.sum()

173

In [120]:
np_ages.sum(axis=1)

array([80, 93])

In [121]:
np_ages.sum(axis=0)

array([43, 76, 54])

In [122]:
np_ages.mean()

28.833333333333332

In [123]:
np_ages.mean(axis=0)

array([21.5, 38. , 27. ])

In [125]:
addition = np.array([[1, 2, 3], [2, 3, 4]])
print(addition)

[[1 2 3]
 [2 3 4]]


In [126]:
np_ages + addition

array([[21, 37, 28],
       [25, 44, 33]])

In [127]:
np_ages - addition

array([[19, 33, 22],
       [21, 38, 25]])

In [128]:
np_ages / addition

array([[20.        , 17.5       ,  8.33333333],
       [11.5       , 13.66666667,  7.25      ]])

In [129]:
np_ages // addition

array([[20, 17,  8],
       [11, 13,  7]])

In [130]:
np_ages * addition

array([[ 20,  70,  75],
       [ 46, 123, 116]])

### Broadcasting

In [137]:
np_ages.shape

(2, 3)

In [138]:
addition = np.array([[10], [50]])
addition.shape

(2, 1)

In [141]:
addition

array([[10],
       [50]])

In [136]:
np_ages + addition

array([[30, 45, 35],
       [73, 91, 79]])

In [142]:
np.hstack([addition, addition, addition]) + np_ages

array([[30, 45, 35],
       [73, 91, 79]])

In [143]:
addition = np.array([[1, 2, 3]])
addition

array([[1, 2, 3]])

In [144]:
addition + np_ages

array([[21, 37, 28],
       [24, 43, 32]])

In [145]:
np_other_ages.shape

(3, 3)

In [146]:
np_ages + np_other_ages

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

### Basic Statistical Operations

In [147]:
np_other_ages

array([[31, 33, 30],
       [21, 33, 20],
       [31, 32, 30]])

In [148]:
np_other_ages.max()

33

In [149]:
np_other_ages.max(axis=1)

array([33, 33, 32])

In [150]:
np_other_ages.max(axis=0)

array([31, 33, 30])

In [151]:
np_other_ages.min()

20

In [152]:
print(np_other_ages.min(axis=1))
print(np_other_ages.min(axis=0))

[30 20 30]
[21 32 20]


In [154]:
print(nd_array)
print(nd_array.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]
(2, 3, 3)


In [155]:
print(nd_array.sum())
print(nd_array.sum(axis=0))
print(nd_array.sum(axis=1))
print(nd_array.sum(axis=2))

180
[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[12 15 18]
 [42 45 48]]
[[ 6 15 24]
 [36 45 54]]


In [161]:
print(nd_array.max())
print(nd_array.max(axis=0))
print(nd_array.max(axis=1))
print(nd_array.max(axis=2))

19
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 7  8  9]
 [17 18 19]]
[[ 3  6  9]
 [13 16 19]]


In [162]:
print(nd_array.std())
print(nd_array.std(axis=0))
print(nd_array.std(axis=1))
print(nd_array.std(axis=2))

5.627314338711377
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
[[2.44948974 2.44948974 2.44948974]
 [2.44948974 2.44948974 2.44948974]]
[[0.81649658 0.81649658 0.81649658]
 [0.81649658 0.81649658 0.81649658]]


In [163]:
nd_array.var()

31.666666666666668

### Dot Product

In [164]:
np_ages

array([[20, 35, 25],
       [23, 41, 29]])

In [165]:
np_other_ages

array([[31, 33, 30],
       [21, 33, 20],
       [31, 32, 30]])

In [166]:
np.dot(np_ages, np_other_ages)

array([[2130, 2615, 2050],
       [2473, 3040, 2380]])

In [167]:
np_ages.dot(np_other_ages)

array([[2130, 2615, 2050],
       [2473, 3040, 2380]])

In [168]:
np.matmul(np_ages, np_other_ages)

array([[2130, 2615, 2050],
       [2473, 3040, 2380]])

In [170]:
np_ages.dot(10)

array([[200, 350, 250],
       [230, 410, 290]])

In [172]:
np_ages * 10

array([[200, 350, 250],
       [230, 410, 290]])

In [171]:
np.matmul(np_ages, 10)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [183]:
a = np.array(
    [
        [[1, 1, 1], [5, 5, 5], [10, 10, 10]],
        [[2, 2, 2], [5, 5, 5], [20, 20, 20]]
    ]
)
b = np.array([[1, 1, 1], [10, 10, 10], [100, 100, 100]])

print(a)
print(b)

[[[ 1  1  1]
  [ 5  5  5]
  [10 10 10]]

 [[ 2  2  2]
  [ 5  5  5]
  [20 20 20]]]
[[  1   1   1]
 [ 10  10  10]
 [100 100 100]]


In [184]:
np.dot(a, b)

array([[[ 111,  111,  111],
        [ 555,  555,  555],
        [1110, 1110, 1110]],

       [[ 222,  222,  222],
        [ 555,  555,  555],
        [2220, 2220, 2220]]])

In [185]:
np.matmul(a, b)

array([[[ 111,  111,  111],
        [ 555,  555,  555],
        [1110, 1110, 1110]],

       [[ 222,  222,  222],
        [ 555,  555,  555],
        [2220, 2220, 2220]]])

## Flatten Array

In [186]:
nd_array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [187]:
flatten_array = nd_array.flatten()
flatten_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [188]:
nd_array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [191]:
ravel_array = nd_array.ravel()
ravel_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [193]:
ravel_array[0] = 10
ravel_array

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [194]:
nd_array

array([[[10,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [195]:
flatten_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [196]:
nd_array.flat

## MSE with NumPy

In [198]:
y = np.array([.1, 1.2, 3.5])
y_hat = np.array([-.1, 2, 3.1])

print(y)
print(y_hat)

[0.1 1.2 3.5]
[-0.1  2.   3.1]


In [201]:
mse = 1/y.size * np.sum((y - y_hat)**2)
mse_square = 1/y.size * np.sum(np.square(y - y_hat))
# mse_mean = np.mean(np.square(y - y_hat))
mse_mean = np.mean((y - y_hat)**2)

print(mse)
print(mse_square)
print(mse_mean)

0.28
0.28
0.28
